# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
